# Generated by Django 5.1.4 on 2025-02-11 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffe', '0002_cartitem_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='coffe',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='image',
            field=models.ImageField(default='images/img-1', upload_to='imgs'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='name',
            field=models.TextField(default='coffee', max_length=500),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
