# Generated by Django 5.1.4 on 2025-02-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffe', '0003_remove_cartitem_coffe_cartitem_image_cartitem_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='coffeid',
            field=models.IntegerField(default=0),
        ),
    ]
