# Generated by Django 5.1.4 on 2025-02-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffe', '0004_cartitem_coffeid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='order_status',
            new_name='orderstatus',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='coffe',
        ),
        migrations.AddField(
            model_name='orders',
            name='coffeid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orders',
            name='image',
            field=models.ImageField(default='images/img-1', upload_to='imgs'),
        ),
        migrations.AddField(
            model_name='orders',
            name='name',
            field=models.TextField(default='coffee', max_length=500),
        ),
        migrations.AddField(
            model_name='orders',
            name='offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
