# Generated by Django 5.1.4 on 2025-02-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffe', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
