# Generated by Django 5.1.4 on 2025-02-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffe', '0008_cartitem_unique_parent_child_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='orderstatus',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], max_length=10),
        ),
    ]
