# Generated by Django 5.1.4 on 2025-02-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffe', '0011_alter_orders_orderstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='orderstatus',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='Pending', max_length=20),
        ),
    ]
